# Generated by Django 5.2.7 on 2025-10-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrowed_on',
            field=models.DateField(),
        ),
    ]
